volumes:
  app_local_postgres_data: {}
  app_local_postgres_data_backups: {}
  app_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: app_local_django
    container_name: app_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: app_production_postgres
    container_name: app_local_postgres
    volumes:
      - app_local_postgres_data:/var/lib/postgresql/data
      - app_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: app_local_redis
    
    volumes:
      - app_local_redis_data:/data
    

  celeryworker:
    <<: *django
    image: app_local_celeryworker
    container_name: app_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: app_local_celerybeat
    container_name: app_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: app_local_flower
    container_name: app_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  ipfs:
    image: ipfs/go-ipfs
    container_name: app_local_ipfs
    ports:
      - "5001:5001"
      - "4001:4001"
      - "8080:8080"
    volumes:
      - .data/ipfs:/data/ipfs