# Generated by Django 5.0.9 on 2024-11-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='is_purchased',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
